### ISSUE TITLE
Data loss while using the app (the variable returns to default value after double screen rotation)

### ISSUE THREAD

**Issue by davirec** [VincentAudibert/CanIDrive#114] opened 2022-03-12 23:25 UTC
When I perform these sequences of events, the variable returns to the default value after double screen rotation:

1. Go to the Main activity
2. Change the default value of the weight variable
3. A screen similar to this will appear:

Before rotation:
<img src="https://user-images.githubusercontent.com/3637419/158038473-52659d85-50cf-412a-b23b-f7fe791b78b1.png" width=30% height=30%>

4. Force the pause from the activity and then return to the activity (double screen rotation). Note that the variable returns to the default value. 

The expected behavior is the return to the previous state with the value of the previous image.

However, the variable returns to the default value.

After rotation:
<img src="https://user-images.githubusercontent.com/3637419/158038476-ba7c8a48-7ad5-4be4-bec2-b3005b2699c9.png" width=30% height=30%>

Note: 
- The pause from activity(1) can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.
- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

Device:
- Device: Moto G30 with OS: Android 11
- Version: 0.2.4
- Device language: English

1. https://developer.android.com/guide/components/activities/activity-lifecycle

**Comment by VincentAudibert** [comment] 2022-04-29 19:19
Duplicate of #115, closing this one.

**Closed as completed by VincentAudibert** 2022-04-29 19:19 UTC
